### ISSUE TITLE
Error : Initializing firebase-admin may fail

### ISSUE THREAD

**Issue by prodwareabdussamad** [dialogflow/fulfillment-bike-shop-nodejs#12]
Dear Team, 

Exception : Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail

I followed the required steps as directed in : https://github.com/dialogflow/fulfillment-bike-shop-nodejs

The appoint is also not created, if I assume this as Simple Warning. 

Any help would be appreciated.

**Comment by findzaatar** [comment]
Duplicate, for reference see [bug](https://github.com/dialogflow/fulfillment-bike-shop-nodejs/issues/11).
