### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by Onlinedispatcher** [dialogflow/fulfillment-bike-shop-nodejs#3]
Hey guys,

thanks a lot for the example. Based on that, I am developing an dialogflow agent, answering messenger messages via fulfillment.

It works perfectly by entering the message directly in the dialogflow console window (for testing)
But when I use the real messenger to receive the message, trigger the intent and perform the fulfilment, I get the following error 

In Dialogflow I can see under History:
"Webhook call failed. Check response JSON for error details".
But if I look into the Raw interactions logs, there is nothing I can see...

In Firebase I can see:
> TypeError: Cannot read property 'source' of undefined
>     at V2Agent.processRequest_ (/user_code/node_modules/dialogflow-fulfillment/src/v2-agent.js:108:86)
>     at new WebhookClient (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:193:17)
>     at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:52:17)
>     at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:26:47)
>     at /var/tmp/worker/worker.js:684:7
>     at /var/tmp/worker/worker.js:668:9
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Although trying different approaches on StackOverflow I still have the issue. 
Probably I am just too blind to see my mistake, can you help me?

This is my fulfillment-code, which is a simplified version of the bike-shop-nodejs-code:

```
'use strict';

const functions = require('firebase-functions');
const {google} = require('googleapis');
const {WebhookClient} = require('dialogflow-fulfillment');

// Enter your calendar ID below and service account JSON below, see https://github.com/dialogflow/bike-shop/blob/master/README.md#calendar-setup
const calendarId = '....(removed)....'
const serviceAccount = {
  "type": "service_account",
  "project_id": "...(removed)....",
  "private_key_id": "...(removed)....",
  "private_key": "...(removed)....",
  "client_email": "...(removed)....",
  "client_id": "...(removed)....",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "...(removed)...."
}; 

// Set up Google Calendar Service account credentials
const serviceAccountAuth = new google.auth.JWT({
  email: serviceAccount.client_email,
  key: serviceAccount.private_key,
  scopes: 'https://www.googleapis.com/auth/calendar'
});

const calendar = google.calendar('v3');
process.env.DEBUG = 'dialogflow:*'; // enables lib debugging statements

const timeZone = 'Europa/Berlin';
const timeZoneOffset = '+02:00';

exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
  const agent = new WebhookClient({ request, response });
  
  function meetingFindDateAndTime (agent) {
    const meetingDateTimeStart = new Date(agent.parameters.date.split('T')[0] + 'T' + agent.parameters.time.split('T')[1]);
    const meetingDateTimeEnd = new Date(new Date(meetingDateTimeStart).setHours(meetingDateTimeStart.getHours() + 1));

    const meetingDateTimeStartString = meetingDateTimeStart.toLocaleString(
      'de-CH',
      { month: 'long', day: 'numeric', hour: 'numeric', timeZone: 'Europe/Berlin' }
    );

    // Check the availability of the time, and make an appointment if there is time on the calendar
    return createCalendarEvent(meetingDateTimeStart, meetingDateTimeEnd).then(() => {
      agent.add(`Ok, das müsste passen: ${meetingDateTimeStartString}. Ich habs im Kalender schonmal geblockt, aber schreibe dir noch eine definitive Zusage.`);
    }).catch(() => {
      agent.add(`Mist, da habe ich leider schon einen Termin. Wann anders?`);
    });
  }

  let intentMap = new Map();
  intentMap.set('meeting.findDateAndTime', meetingFindDateAndTime);
  agent.handleRequest(intentMap);
});

function createCalendarEvent (dateTimeStart, dateTimeEnd) {
  return new Promise((resolve, reject) => {
    calendar.events.list({
      auth: serviceAccountAuth, // List events for time period
      calendarId: calendarId,
      timeMin: dateTimeStart.toISOString(),
      timeMax: dateTimeEnd.toISOString()
    }, (err, calendarResponse) => {
      // Check if there is a event already on the Bike Shop Calendar
      if (err || calendarResponse.data.items.length > 0) {
        reject(err || new Error('Requested time conflicts with another appointment'));
      } else {
        // Create event for the requested time period
        calendar.events.insert({ auth: serviceAccountAuth,
          calendarId: calendarId,
          resource: {summary: 'Bike Appointment',
            start: {dateTime: dateTimeStart},
            end: {dateTime: dateTimeEnd}}
        }, (err, event) => {
          err ? reject(err) : resolve(event);
        }
        );
      }
    });
  });
}
```

**Comment by sarahdwyer** [comment]
Under your meetingFindDateAndTime function, you defined the variable meetingDateTimeStart without including timeZoneOffset, I would try:  

```javascript 
const meetingDateTimeStart = new Date(Date.parse(agent.parameters.date.split('T')[0] + 'T' + agent.parameters.time.split('T')[1].split('-')[0] + timeZoneOffset)); 
```

**Comment by Onlinedispatcher** [comment]
Thanks, but adding the timeZoneOffset does not help.

Still:
```
TypeError: Cannot read property 'source' of undefined
    at V2Agent.processRequest_ (/user_code/node_modules/dialogflow-fulfillment/src/v2-agent.js:108:86)
```

I really do not get it ... :(

**Comment by matthewayne** [comment]
What version of the library are you using?  Try upgrading to `dialogflow-fulfillment` to `0.4.1` if you haven't already.

**Comment by Onlinedispatcher** [comment]
@matthewayne Absolutely right, I was still using an 0.3 beta version.
After adding
    "dialogflow-fulfillment": "^0.4.1",
    "actions-on-google": "^2.1.3"
it worked the same, inside the console windows and via the actual messenger.

Nice!!!! Thanks a lot!

**Comment by saife245** [comment]
can anybody help to get out of this, 

exports.dialogflowFirebaseFulfillment = (req, res) => {
  console.log('Dialogflow Request body: ' + JSON.stringify(req.body));
  let type = req.body.queryResult.outputContexts[1].parameters['prod.original'];
  let bank = req.body.queryResult.outputContexts[1].parameters['bank.original'];
  console.log('looking for ' + type);
  console.log('bank is '+ bank);
  let quote_type = bank.toUpperCase();
  if (type.toLowerCase() == 'swift code'){
     if (quote_type == "SBI") { 
         return datastore.runQuery(query1).then(results => {
            res.ask(results[0][0].code);
        });
     } else if (quote_type == "DBS") {
         return datastore.runQuery(query2).then(results => {
            res.ask(results[0][0].code);
        });
     } else if (quote_type == "RBL") {
         return datastore.runQuery(query3).then(results => {
            res.ask(results[0][0].code);
           //conv.add(JSON.stringify({ 'fulfillmentText':results[0][0].code }));
        });
     } else {
            res.ask("get off your ass and work instead of talking to me");
     }
  }
}

The above code is for reading the datastore of kind 'swift', I will give the bank name it response the bank swift code but eventually, it crashes all time.
