### ISSUE TITLE
Error in creating agent

### ISSUE THREAD

**Issue by awais786327** [dialogflow/fulfillment-bike-shop-nodejs#7]
Hi, can you please take a look at this, cuz ama having error in creating agent

![image](https://user-images.githubusercontent.com/12613564/44979394-806e7080-af86-11e8-9909-f5421c36251e.png)

**Comment by Manojbv** [comment]
Facing the same issue

**Comment by sarahdwyer** [comment]
@awais786327 @Manojbv Fixed!
